import { parse, stringify } from 'yaml'
import baseConfigYaml from '../../../config/config.yaml?raw'
import type { Asset, MandateDraft } from './types'

export const MIN_ASSETS = 5
export const MAX_ASSETS = 55

/** yfinance-style ticker: letters/digits plus . - = ^ (e.g. SPY, HG=F, ^N225, BTC-USD). */
export const TICKER_PATTERN = /^[A-Z0-9^][A-Z0-9.\-=^]{0,14}$/

export const ENSEMBLE_SEEDS = [42, 101, 777, 2024, 31337]

export function slugify(name: string, separator = '_'): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, separator)
      .replace(new RegExp(`^\\${separator}+|\\${separator}+$`, 'g'), '') || 'mandate'
  )
}

export function assetIdFor(name: string, existing: Asset[]): string {
  const base = slugify(name)
  if (!existing.some((asset) => asset.id === base)) return base
  let n = 2
  while (existing.some((asset) => asset.id === `${base}_${n}`)) n += 1
  return `${base}_${n}`
}

/**
 * Validation of the fields the engine actually enforces. Advisory metadata
 * (min cash, turnover budget, objective) never gates the workflow.
 */
export function validateDraft(draft: MandateDraft): string[] {
  const errors: string[] = []
  const assets = draft.assets.filter((asset) => asset.enabled)

  if (!draft.name.trim()) errors.push('Mandate name is required.')
  if (!(draft.capital > 0)) errors.push('Starting capital must be positive.')
  if (assets.length < MIN_ASSETS) errors.push(`Select at least ${MIN_ASSETS} assets (${assets.length} selected).`)
  if (assets.length > MAX_ASSETS) errors.push(`The engine supports at most ${MAX_ASSETS} assets (${assets.length} selected).`)

  const ids = new Set<string>()
  const tickers = new Set<string>()
  for (const asset of assets) {
    if (ids.has(asset.id)) errors.push(`Duplicate asset id "${asset.id}".`)
    ids.add(asset.id)
    const ticker = asset.ticker.toUpperCase()
    if (tickers.has(ticker)) errors.push(`Duplicate ticker "${asset.ticker}".`)
    tickers.add(ticker)
    if (!TICKER_PATTERN.test(ticker)) errors.push(`Ticker "${asset.ticker}" is not a valid data-source symbol.`)
  }

  if (draft.maxAssetWeight * assets.length < 100) {
    errors.push(
      `A ${draft.maxAssetWeight}% cap across ${assets.length} assets cannot reach full investment. ` +
        'Raise the cap or add assets.',
    )
  }
  if (!assets.some((asset) => asset.id === draft.benchmarkAssetId)) {
    errors.push('The evaluation benchmark must be one of the selected assets.')
  }
  return errors
}

/**
 * Materialize a complete engine config from the repository base config.
 * Only fields the engine enforces are changed; per-asset holding costs are
 * preserved from each asset's configured value (never zeroed).
 */
export function buildConfigYaml(draft: MandateDraft): string {
  const assets = draft.assets.filter((asset) => asset.enabled)
  const config = parse(baseConfigYaml) as Record<string, Record<string, unknown>>

  config.universe.assets = Object.fromEntries(assets.map((asset) => [asset.id.toUpperCase(), asset.ticker]))
  config.universe.benchmark = (
    assets.find((asset) => asset.id === draft.benchmarkAssetId) ?? assets[0]
  ).id.toUpperCase()
  config.environment.initial_cash = draft.capital
  config.environment.max_single_asset_weight = draft.maxAssetWeight / 100
  config.environment.stop_loss_fraction = draft.stopLoss / 100
  config.reward.benchmark_cap_weights = assets.map(() => 1 / assets.length)
  config.reward.concentration_target_eff_assets = Math.max(2, Math.min(6, assets.length - 1))
  config.transaction_costs.slippage = assets.map((asset) => asset.slippageBps / 10_000)
  config.transaction_costs.tx_fee = assets.map((asset) => asset.feeBps / 10_000)
  config.transaction_costs.annual_holding_cost = assets.map((asset) => asset.holdingCostBps / 10_000)
  config.training.timesteps = draft.trainingBudget
  config.training.reproducible = draft.reproducible

  const metadata = [
    '# Generated by MarketTrainer Mandate Builder from config/config.yaml.',
    '# Engine-enforced fields are materialized below. The advisory fields in this',
    '# header are mandate metadata only — they do NOT change engine behavior.',
    `# mandate_name: ${JSON.stringify(draft.name)}`,
    `# base_currency: ${draft.baseCurrency}`,
    `# advisory_min_cash_percent: ${draft.minCash}`,
    `# advisory_max_annual_turnover_percent: ${draft.maxTurnover}`,
    `# advisory_objective: ${draft.objective}`,
    `# requested_seed_count: ${draft.seedCount}`,
    '',
  ].join('\n')

  return metadata + stringify(config, { lineWidth: 100 })
}

/** SHA-256 of the generated YAML, for provenance display and file naming. */
export async function configSha256(yamlText: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(yamlText))
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('')
}

export function downloadConfig(draft: MandateDraft, hash?: string) {
  const slug = slugify(draft.name, '-')
  const suffix = hash ? `-${hash.slice(0, 8)}` : ''
  const blob = new Blob([buildConfigYaml(draft)], { type: 'text/yaml;charset=utf-8' })
  const href = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = href
  link.download = `${slug}${suffix}.yaml`
  link.click()
  URL.revokeObjectURL(href)
}

export type RunPlan = {
  cohort: string
  seeds: number[]
  windows: number[]
  totalJobs: number
  commands: string[]
}

/**
 * Full walk-forward run plan: one seed-ensemble invocation per canonical
 * window (W1–W5), covering every requested seed — not a single-window command.
 */
export function buildRunPlan(draft: MandateDraft): RunPlan {
  const cohort = slugify(draft.name)
  const seeds = ENSEMBLE_SEEDS.slice(0, draft.seedCount)
  const windows = [1, 2, 3, 4, 5]
  const configFile = `config/cohorts/${cohort}.yaml`
  const commands = [
    `# 1. Review the exported YAML, then place it at ${configFile}`,
    `# 2. Preflight it against the live engine parser:`,
    `python scripts/preflight.py --config ${configFile}`,
    `# 3. Launch the walk-forward cohort (${windows.length} windows x ${seeds.length} seeds):`,
    ...windows.map(
      (window) =>
        `scripts/run_seed_ensemble.sh --cohort ${cohort} --seeds "${seeds.join(' ')}" -- --window ${window} --config ${configFile} --refresh-data`,
    ),
  ]
  return { cohort, seeds, windows, totalJobs: windows.length * seeds.length, commands }
}
